import link_img from "../../assets/LinkImg";
export const cardsTop = [
  {
    img: link_img.terrifyingVersionPlague,
    name: "Plague",
    ability: "Epidemic Mastery",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.Roach,
    name: "Roach",
    ability: "Pestilence Aura",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.TerrorSurgeon,
    name: "Terror Surgeon",
    ability: "Mask of Horror",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.jungleStalker,
    name: "Sharp Shot",
    ability: "Cursed Bullet",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.Phantasm,
    name: "Phantasm",
    ability: "Stellar Collapse",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.BlastForge,
    name: "Blast Forge",
    ability: "Chemical Chaos",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.Mechanix,
    name: "Mechanix",
    ability: "Nano-Repair",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.IceBreaker,
    name: "Ice Breaker",
    ability: "Polar Vortex",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.DeathWraith,
    name: "Death Wraith",
    ability: "Soul Drain",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.VoodooShaman,
    name: "Voodoo Shaman",
    ability: "Mind Meld",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.venomBite,
    name: "Venom Bite",
    ability: "Paralyzing Venom",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.Cyclope,
    name: "Cyclope",
    ability: "Gaze of Petrification",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.Dyno,
    name: "Dyno",
    ability: "Meteor Impact",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.herculesDota2,
    name: "Hercules",
    ability: "Eternal Champion",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.DarkJester,
    name: "Dark Jester",
    ability: "Eternal Laughter",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.KingMonk,
    name: "KingMonk",
    ability: "Island's Wrath",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.ShadowLurker,
    name: "Shadow Lurker",
    ability: "ShadowLurker",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.Dreamweaver,
    name: "Dreamweaver",
    ability: "Nightmare's Embrace",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.Voidscorn,
    name: "Voidscorn",
    ability: "Singularity Grasp",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.BloodLord,
    name: "BloodLord",
    ability: "Artifact of Night's Embrace",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.romanGodLike,
    name: "War Deity",
    ability: "Siegebreaker Aura",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.TrickLord,
    name: "Trick Lord",
    ability: "Veil of Shadows",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.TideForm,
    name: "Tide Form",
    ability: "Hydro Shield",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.GreenWard,
    name: "Green Ward",
    ability: "Eternal Growth",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.PlagueShadow,
    name: "Plague Shadow",
    ability: "Decay Wave",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.SwiftBlade,
    name: "Swift Blade",
    ability: "Blade Rush",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.ShadowKill,
    name: "Shadow Kill",
    ability: "Shadow Strike",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.MirageBlade,
    name: "Mirage Blade",
    ability: "Dune Strike",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.SolFlare,
    name: "Sol Flare ",
    ability: "Solar Burst",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.NetherSoul,
    name: "Nether Soul",
    ability: "Realm of Shadows",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.SpellCraft,
    name: "Spell Craft",
    ability: "Spell Amplification",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.DuneSlayer,
    name: "Dune Slayer",
    ability: "Desert's Wrath",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.AbyssFiend,
    name: "Abyss Fiend",
    ability: "Shadow of the Depths",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.emberWarrior,
    name: "Wild Fire",
    ability: "Solar Flare",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.FrostMark,
    name: "Frost Mark",
    ability: "Icicle Arrow",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.TerraShift,
    name: "Terra Shift",
    ability: "Seismic Slam",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.QuakeFist,
    name: "Quake Fist",
    ability: "Tremor Punch",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.VoidReign,
    name: "Void Reign",
    ability: "Cosmic Rift",
    icon: link_img.iconArcher,
  },
];

export const cardsBottom = [
  {
    img: link_img.SlickShot,
    name: "Slick Shot",
    ability: "Silent Arrow",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.BladeStorm,
    name: "Blade Storm",
    ability: "Monstrous Slash",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.TideBlade,
    name: "Tide Blade",
    ability: "Abyssal Strike",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.chaosRend,
    name: "SoulRend",
    ability: "Essence Drain",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.ruggedFigureResembling,
    name: "Toxic Skin",
    ability: "Bristle Barrage",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.NatureBin,
    name: "Nature Bin",
    ability: "Verdant Strike",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.WildKin,
    name: "Wild Kin",
    ability: "Beast Call",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.CrimsonHound,
    name: "Crimson Hound",
    ability: "Blood Hunt",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.TreasureSeek,
    name: "Treasure Seek",
    ability: "Tracking Dart",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.QuillBrute,
    name: "Quill Brute",
    ability: "Quill Spray",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.WebQueen,
    name: "Web Queen",
    ability: "Web Dominion",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.DarkRider,
    name: "Dark Rider",
    ability: "Shadow Charge",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.SkyGlider,
    name: "Sky Glider",
    ability: "Aerial Lung",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.agileArcher,
    name: "Ember Arch",
    ability: "Flame Volley",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.GearHart,
    name: "Gear Hart",
    ability: "Steam Blast",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.FrostBelle,
    name: "Frost Belle",
    ability: "Glacial Cascade",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.ShadowMyst,
    name: "Shadow Myst",
    ability: "Veil of Shadows",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.StarHammer,
    name: "Star Hammer",
    ability: "Meteor Strike",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.HexSinger,
    name: "Hex Singer",
    ability: "Blood Hunt",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.StormWield,
    name: "Storm Wield",
    ability: "Lightning Strike",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.NightShade,
    name: "Night Shade ",
    ability: "Ethereal Slash",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.SpellBane,
    name: "Spell Bane",
    ability: "Blood Hunt",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.SparkGuard,
    name: "Spark Guard",
    ability: "Electro Pulse",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.DreamFiend,
    name: "Dream Fiend",
    ability: "Nightmare Grasp",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.FearAura,
    name: "Fear Aura",
    ability: "Fear Aura",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.SilenceStrike,
    name: "Silence Strike",
    ability: "Silencing Wave",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.ShadowPoison,
    name: "Shadow Poison",
    ability: "Venomous Gale",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.wardDraconic,
    name: "Plague Ward",
    ability: "Toxic Breath",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.Zathor,
    name: "Zathor, the Abyssal Terror",
    ability: "Shadow Surge",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.Dreadfang,
    name: "Dreadfang, the Abyssal Terror",
    ability: "Abyssal Roar",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.Sylvanthea2,
    name: "Sylvanthea, Guardian of the Enchanted Forest",
    ability: "Nature's Embrace",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.AbyssalAberration,
    name: "Abyssal Aberration",
    ability: "Unknown",
    icon: link_img.iconArcher,
  },
  {
    img: link_img.Verminathrax,
    name: "Verminathrax, the Plague Bringer",
    ability: "Swarm of Despair",
    icon: link_img.iconArcher,
  },
];
