name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Hosting
        uses: easingthemes/ssh-deploy@v2
        with:
          REMOTE_HOST: 188.120.235.169
          REMOTE_USER: root
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: dist
          TARGET: /var/www/www-root/data/www/georgedotgame.fvds.ru
